rabbitmq:
  image: rabbitmq
  ports:
   - "5672:5672"
  environment:
   - RABBITMQ_NODENAME=rabbitmq
postgres:
  image: postgres
  ports:
   - "5432:5432"
  environment:
   - POSTGRES_PASSWORD=postgres
elasticsearch:
  image: elasticsearch
  ports: 
    - "9200:9200"
    - "9300:9300"